# Generated by Django 5.0.6 on 2024-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.CharField(choices=[('sale_product', 'محصول تخفیف دارد/ندارد')], db_index=True, default=1, max_length=300),
            preserve_default=False,
        ),
    ]
