# Generated by Django 5.0.6 on 2024-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.CharField(default=False, null=True),
        ),
    ]
