# Generated by Django 5.0.6 on 2024-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.CharField(choices=[('sale_product', 'محصول تخفیف دارد')], db_index=True, max_length=300),
        ),
    ]
