# Generated by Django 5.0.6 on 2024-07-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, null=True, verbose_name='محصول تخفیف دارد./ندارد'),
        ),
        migrations.CreateModel(
            name='product_galry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/galry')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('product_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='گالری')),
            ],
        ),
    ]
