# Generated by Django 5.0.6 on 2024-07-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='دسته بنده'),
        ),
    ]
