# Generated by Django 5.0.6 on 2024-07-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام برند(به فارسی)')),
                ('title_english', models.CharField(max_length=200, verbose_name='نام برند(به انگلیسی)')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('url_name', models.CharField(max_length=400, verbose_name='عنوان در url(به انگلیسی)')),
            ],
            options={
                'verbose_name': 'برندها',
                'verbose_name_plural': 'برند',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='برند'),
        ),
    ]
