# Generated by Django 5.0.6 on 2024-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_category_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='title',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='url_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان(به فارسی)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.CharField(max_length=300, verbose_name='عنوان در url(به انگلیسی)'),
        ),
    ]
