# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_brands_is_active_remove_brands_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='brands',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده'),
        ),
        migrations.AddField(
            model_name='brands',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='عنوان(به فارسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='url_name',
            field=models.CharField(default=2, max_length=300, verbose_name='عنوان در url(به انگلیسی)'),
            preserve_default=False,
        ),
    ]
